- alias: "Status Sonoff on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoff/POWER1"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoff/POWER2"
        payload: ""

- alias: "Theme for day/night"
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sun.sun
      to: above_horizon
    - platform: state
      entity_id: sun.sun
      to: below_horizon
  action:
    service_template: frontend.set_theme
    data_template:
      name: >
        {% if states.sun.sun.state == "above_horizon" %}
          default
        {% else %}
          darkcyan
        {% endif %}
