- alias: "Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoff/POWER1"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoff/POWER2"
        payload: ""
